namespace Wcf.Extensions.OpenIdConnect.Specs.Support
{
    internal static class SpecConstants
    {
        public const string ConfigurationWithAccessTokenIssuer =
            "{\"issuer\":\"https:\\/\\/ADFS.johan.local\\/adfs\",\"authorization_endpoint\":\"https:\\/\\/adfs.johan.local\\/adfs\\/oauth2\\/authorize\\/\",\"token_endpoint\":\"https:\\/\\/adfs.johan.local\\/adfs\\/oauth2\\/token\\/\",\"jwks_uri\":\"https:\\/\\/adfs.johan.local\\/adfs\\/discovery\\/keys\",\"token_endpoint_auth_methods_supported\":[\"client_secret_post\",\"client_secret_basic\",\"private_key_jwt\",\"windows_client_authentication\"],\"response_types_supported\":[\"code\",\"id_token\",\"code id_token\",\"id_token token\",\"code token\",\"code id_token token\"],\"response_modes_supported\":[\"query\",\"fragment\",\"form_post\"],\"grant_types_supported\":[\"authorization_code\",\"refresh_token\",\"client_credentials\",\"urn:ietf:params:oauth:grant-type:jwt-bearer\",\"implicit\",\"password\",\"srv_challenge\"],\"subject_types_supported\":[\"pairwise\"],\"scopes_supported\":[\"write\",\"aza\",\"openid\",\"user_impersonation\",\"email\",\"logon_cert\",\"allatclaims\",\"vpn_cert\",\"johan\",\"profile\",\"winhello_cert\",\"johan2\"],\"id_token_signing_alg_values_supported\":[\"RS256\"],\"token_endpoint_auth_signing_alg_values_supported\":[\"RS256\"],\"access_token_issuer\":\"http:\\/\\/ADFS.johan.local\\/adfs\\/services\\/trust\",\"claims_supported\":[\"aud\",\"iss\",\"iat\",\"exp\",\"auth_time\",\"nonce\",\"at_hash\",\"c_hash\",\"sub\",\"upn\",\"unique_name\",\"pwd_url\",\"pwd_exp\",\"sid\"],\"microsoft_multi_refresh_token\":true,\"userinfo_endpoint\":\"https:\\/\\/adfs.johan.local\\/adfs\\/userinfo\",\"capabilities\":[],\"end_session_endpoint\":\"https:\\/\\/adfs.johan.local\\/adfs\\/oauth2\\/logout\",\"as_access_token_token_binding_supported\":true,\"as_refresh_token_token_binding_supported\":true,\"resource_access_token_token_binding_supported\":true,\"op_id_token_token_binding_supported\":true,\"rp_id_token_token_binding_supported\":true,\"frontchannel_logout_supported\":true,\"frontchannel_logout_session_supported\":true}";

        public const string ConfigurationWithoutAccessTokenIssuer =
            "{\"issuer\":\"https:\\/\\/ADFS.johan.local\\/adfs\",\"authorization_endpoint\":\"https:\\/\\/adfs.johan.local\\/adfs\\/oauth2\\/authorize\\/\",\"token_endpoint\":\"https:\\/\\/adfs.johan.local\\/adfs\\/oauth2\\/token\\/\",\"jwks_uri\":\"https:\\/\\/adfs.johan.local\\/adfs\\/discovery\\/keys\",\"token_endpoint_auth_methods_supported\":[\"client_secret_post\",\"client_secret_basic\",\"private_key_jwt\",\"windows_client_authentication\"],\"response_types_supported\":[\"code\",\"id_token\",\"code id_token\",\"id_token token\",\"code token\",\"code id_token token\"],\"response_modes_supported\":[\"query\",\"fragment\",\"form_post\"],\"grant_types_supported\":[\"authorization_code\",\"refresh_token\",\"client_credentials\",\"urn:ietf:params:oauth:grant-type:jwt-bearer\",\"implicit\",\"password\",\"srv_challenge\"],\"subject_types_supported\":[\"pairwise\"],\"scopes_supported\":[\"write\",\"aza\",\"openid\",\"user_impersonation\",\"email\",\"logon_cert\",\"allatclaims\",\"vpn_cert\",\"johan\",\"profile\",\"winhello_cert\",\"johan2\"],\"id_token_signing_alg_values_supported\":[\"RS256\"],\"token_endpoint_auth_signing_alg_values_supported\":[\"RS256\"],\"claims_supported\":[\"aud\",\"iss\",\"iat\",\"exp\",\"auth_time\",\"nonce\",\"at_hash\",\"c_hash\",\"sub\",\"upn\",\"unique_name\",\"pwd_url\",\"pwd_exp\",\"sid\"],\"microsoft_multi_refresh_token\":true,\"userinfo_endpoint\":\"https:\\/\\/adfs.johan.local\\/adfs\\/userinfo\",\"capabilities\":[],\"end_session_endpoint\":\"https:\\/\\/adfs.johan.local\\/adfs\\/oauth2\\/logout\",\"as_access_token_token_binding_supported\":true,\"as_refresh_token_token_binding_supported\":true,\"resource_access_token_token_binding_supported\":true,\"op_id_token_token_binding_supported\":true,\"rp_id_token_token_binding_supported\":true,\"frontchannel_logout_supported\":true,\"frontchannel_logout_session_supported\":true}";

        public const string ConfigurationWithoutJwksUri =
            "{\"issuer\":\"https:\\/\\/ADFS.johan.local\\/adfs\",\"authorization_endpoint\":\"https:\\/\\/adfs.johan.local\\/adfs\\/oauth2\\/authorize\\/\",\"token_endpoint\":\"https:\\/\\/adfs.johan.local\\/adfs\\/oauth2\\/token\\/\",\"token_endpoint_auth_methods_supported\":[\"client_secret_post\",\"client_secret_basic\",\"private_key_jwt\",\"windows_client_authentication\"],\"response_types_supported\":[\"code\",\"id_token\",\"code id_token\",\"id_token token\",\"code token\",\"code id_token token\"],\"response_modes_supported\":[\"query\",\"fragment\",\"form_post\"],\"grant_types_supported\":[\"authorization_code\",\"refresh_token\",\"client_credentials\",\"urn:ietf:params:oauth:grant-type:jwt-bearer\",\"implicit\",\"password\",\"srv_challenge\"],\"subject_types_supported\":[\"pairwise\"],\"scopes_supported\":[\"write\",\"aza\",\"openid\",\"user_impersonation\",\"email\",\"logon_cert\",\"allatclaims\",\"vpn_cert\",\"johan\",\"profile\",\"winhello_cert\",\"johan2\"],\"id_token_signing_alg_values_supported\":[\"RS256\"],\"token_endpoint_auth_signing_alg_values_supported\":[\"RS256\"],\"access_token_issuer\":\"http:\\/\\/ADFS.johan.local\\/adfs\\/services\\/trust\",\"claims_supported\":[\"aud\",\"iss\",\"iat\",\"exp\",\"auth_time\",\"nonce\",\"at_hash\",\"c_hash\",\"sub\",\"upn\",\"unique_name\",\"pwd_url\",\"pwd_exp\",\"sid\"],\"microsoft_multi_refresh_token\":true,\"userinfo_endpoint\":\"https:\\/\\/adfs.johan.local\\/adfs\\/userinfo\",\"capabilities\":[],\"end_session_endpoint\":\"https:\\/\\/adfs.johan.local\\/adfs\\/oauth2\\/logout\",\"as_access_token_token_binding_supported\":true,\"as_refresh_token_token_binding_supported\":true,\"resource_access_token_token_binding_supported\":true,\"op_id_token_token_binding_supported\":true,\"rp_id_token_token_binding_supported\":true,\"frontchannel_logout_supported\":true,\"frontchannel_logout_session_supported\":true}";

        public const string ConfigurationKeys =
            "{\"keys\":[{\"kty\":\"RSA\",\"use\":\"sig\",\"alg\":\"RS256\",\"kid\":\"US4ypvt2KO_IxQuDHnsVfMLjihw\",\"x5t\":\"US4ypvt2KO_IxQuDHnsVfMLjihw\",\"n\":\"lwTMqdN_uVS-ePv35u0u4pSpAo4Nz-LpxukN9Cc3TYHg30KbwpMb9Lit5pX5ZSPvybGJGc8sn8ZwkWrVrTWcaMbrSkAvVIOFeNYF6-fRznh7dmebVhjSw2gAZ788My1N-hO4hNRRd0eiVm7XzDbOSlWDm7Wi9BEYp4JkWfkbWxGrXGkTn7F6rG36XxW1cJE-vn52jVxm5CfyQa6D8rv0Wyy9jN07xHXoHtmioC8CFTaFRkbaJ6z8PrXndo_7uvfzY8S1tDs8hQzJdclZ35MEH3KERbyKwWXBqoYLgCAcfgwkACiX1e1oEFhSv2XGjk95BCLxybc1GKxppDp_muygWw\",\"e\":\"AQAB\",\"x5c\":[\"MIIC3DCCAcSgAwIBAgIQXntUH\\/PYurdMCUWXsCaSoTANBgkqhkiG9w0BAQsFADAqMSgwJgYDVQQDEx9BREZTIFNpZ25pbmcgLSBBREZTLmpvaGFuLmxvY2FsMB4XDTE3MDgxNzEzNTkzN1oXDTE4MDgxNzEzNTkzN1owKjEoMCYGA1UEAxMfQURGUyBTaWduaW5nIC0gQURGUy5qb2hhbi5sb2NhbDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJcEzKnTf7lUvnj79+btLuKUqQKODc\\/i6cbpDfQnN02B4N9Cm8KTG\\/S4reaV+WUj78mxiRnPLJ\\/GcJFq1a01nGjG60pAL1SDhXjWBevn0c54e3Znm1YY0sNoAGe\\/PDMtTfoTuITUUXdHolZu18w2zkpVg5u1ovQRGKeCZFn5G1sRq1xpE5+xeqxt+l8VtXCRPr5+do1cZuQn8kGug\\/K79FssvYzdO8R16B7ZoqAvAhU2hUZG2ies\\/D6153aP+7r382PEtbQ7PIUMyXXJWd+TBB9yhEW8isFlwaqGC4AgHH4MJAAol9XtaBBYUr9lxo5PeQQi8cm3NRisaaQ6f5rsoFsCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAB0+hInSuUmIAKddKzRDr\\/SMlFW0jfegR3NgsxRPumle\\/u2fSW4YWUi204xYBeE3XdxbN7btHFuCCvcd6T82nn4rO8Oy1W5yi5uT7iCYB6dC\\/asoZZZv7uCXSMiYoEeCZkcR3qAyHpGGc+e2N8ykfaSlZzzf\\/KZpnuUq8j6Mu72fg27eT1V0BkyjkxCwxRzgWWA1X97aw2PZGGQb8uSy+HrUr+8maqJVujw9JzeJGjUQaN5EPhh\\/GuTDciEBueRrE9bZ9X3Ztwe71E54QDx1ewAO7O4XcWgZACyQLSrXBmX0vUqeebSQYmkz\\/lmezermgzzJnIulAWOr1AHS5hF+0rQ==\"]}]}";

        public const string ConfigurationKeysWithoutX5CCertificate =
            "{\"keys\":[{\"kty\":\"RSA\",\"use\":\"sig\",\"alg\":\"RS256\",\"kid\":\"US4ypvt2KO_IxQuDHnsVfMLjihw\",\"x5t\":\"US4ypvt2KO_IxQuDHnsVfMLjihw\",\"n\":\"lwTMqdN_uVS-ePv35u0u4pSpAo4Nz-LpxukN9Cc3TYHg30KbwpMb9Lit5pX5ZSPvybGJGc8sn8ZwkWrVrTWcaMbrSkAvVIOFeNYF6-fRznh7dmebVhjSw2gAZ788My1N-hO4hNRRd0eiVm7XzDbOSlWDm7Wi9BEYp4JkWfkbWxGrXGkTn7F6rG36XxW1cJE-vn52jVxm5CfyQa6D8rv0Wyy9jN07xHXoHtmioC8CFTaFRkbaJ6z8PrXndo_7uvfzY8S1tDs8hQzJdclZ35MEH3KERbyKwWXBqoYLgCAcfgwkACiX1e1oEFhSv2XGjk95BCLxybc1GKxppDp_muygWw\",\"e\":\"AQAB\",\"x5c\":[]}]}";

        public const string ConfigurationKeysWithoutX5CProperty =
            "{\"keys\":[{\"kty\":\"RSA\",\"use\":\"sig\",\"alg\":\"RS256\",\"kid\":\"US4ypvt2KO_IxQuDHnsVfMLjihw\",\"x5t\":\"US4ypvt2KO_IxQuDHnsVfMLjihw\",\"n\":\"lwTMqdN_uVS-ePv35u0u4pSpAo4Nz-LpxukN9Cc3TYHg30KbwpMb9Lit5pX5ZSPvybGJGc8sn8ZwkWrVrTWcaMbrSkAvVIOFeNYF6-fRznh7dmebVhjSw2gAZ788My1N-hO4hNRRd0eiVm7XzDbOSlWDm7Wi9BEYp4JkWfkbWxGrXGkTn7F6rG36XxW1cJE-vn52jVxm5CfyQa6D8rv0Wyy9jN07xHXoHtmioC8CFTaFRkbaJ6z8PrXndo_7uvfzY8S1tDs8hQzJdclZ35MEH3KERbyKwWXBqoYLgCAcfgwkACiX1e1oEFhSv2XGjk95BCLxybc1GKxppDp_muygWw\",\"e\":\"AQAB\"}]}";

        public const string ConfigurationKeysWithoutKeys =
            "{\"keys\":[]}";

        public const string ConfigurationKeysWithoutKeyProperty =
            "{}";

        public const string Certificate =
                "MIIC3DCCAcSgAwIBAgIQXntUH/PYurdMCUWXsCaSoTANBgkqhkiG9w0BAQsFADAqMSgwJgYDVQQDEx9BREZTIFNpZ25pbmcgLSBBREZTLmpvaGFuLmxvY2FsMB4XDTE3MDgxNzEzNTkzN1oXDTE4MDgxNzEzNTkzN1owKjEoMCYGA1UEAxMfQURGUyBTaWduaW5nIC0gQURGUy5qb2hhbi5sb2NhbDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJcEzKnTf7lUvnj79+btLuKUqQKODc/i6cbpDfQnN02B4N9Cm8KTG/S4reaV+WUj78mxiRnPLJ/GcJFq1a01nGjG60pAL1SDhXjWBevn0c54e3Znm1YY0sNoAGe/PDMtTfoTuITUUXdHolZu18w2zkpVg5u1ovQRGKeCZFn5G1sRq1xpE5+xeqxt+l8VtXCRPr5+do1cZuQn8kGug/K79FssvYzdO8R16B7ZoqAvAhU2hUZG2ies/D6153aP+7r382PEtbQ7PIUMyXXJWd+TBB9yhEW8isFlwaqGC4AgHH4MJAAol9XtaBBYUr9lxo5PeQQi8cm3NRisaaQ6f5rsoFsCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAB0+hInSuUmIAKddKzRDr/SMlFW0jfegR3NgsxRPumle/u2fSW4YWUi204xYBeE3XdxbN7btHFuCCvcd6T82nn4rO8Oy1W5yi5uT7iCYB6dC/asoZZZv7uCXSMiYoEeCZkcR3qAyHpGGc+e2N8ykfaSlZzzf/KZpnuUq8j6Mu72fg27eT1V0BkyjkxCwxRzgWWA1X97aw2PZGGQb8uSy+HrUr+8maqJVujw9JzeJGjUQaN5EPhh/GuTDciEBueRrE9bZ9X3Ztwe71E54QDx1ewAO7O4XcWgZACyQLSrXBmX0vUqeebSQYmkz/lmezermgzzJnIulAWOr1AHS5hF+0rQ==";
    }
}